cc_library(
    name = "single_cpu",
    srcs = ["merge_sort.cc"],
    hdrs = ["merge_sort.h"],
    copts = [
        "-std=c++20",
        "-pthread",
        "-O3",
    ],
    visibility = ["//visibility:public"],
)
