cc_library(
    name = "utils",
    srcs = [
        "benchmark/benchmark.cc",
        "benchmark/benchmark_result.cc",
    ],
    hdrs = [
        "benchmark/benchmark.h",
        "benchmark/benchmark_result.h",
    ],
    visibility = ["//visibility:public"],
    copts = ["-std=c++20"],
)
