cc_library(
    name = "utils",
    srcs = [
        "benchmark/benchmark_result.cc",
        "benchmark/sort_benchmark.cc",
    ],
    hdrs = [
        "benchmark/benchmark_result.h",
        "benchmark/sort_benchmark.h",
    ],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)
